version: '3.8'

services:
  kong:
    image: kong:3.7
    container_name: kong
    restart: always
    volumes:
      - ./plugins/sensitive-encrypt:/usr/local/share/lua/5.1/kong/plugins/sensitive-encrypt
      - ./kong.yml:/etc/kong/kong.yml:ro
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_MANAGER_LISTEN: "0.0.0.0:8002"
      KONG_PORTAL_GUI_HOST: "localhost:8003"
      KONG_PORTAL: "on"
      KONG_PLUGINS: bundled,ai-proxy,sensitive-encrypt
      KONG_UNTRUSTED_LUA: "on"
      KONG_LUA_PACKAGE_PATH: /usr/local/share/lua/5.1/?.lua;;
    command: ["kong", "docker-start"]
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8003:8003"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana-enterprise:9.5.1  # Use specific version
    container_name: grafana
    restart: unless-stopped
    ports:
      - "9000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_INSTALL_PLUGINS: ""  # Explicitly set empty plugins
    volumes:
      - grafana-data:/var/lib/grafana
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      kong:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      kong:
        condition: service_healthy

volumes:
  grafana-data: